# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_quotes_quoted_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
