# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_auto_20170721_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favorites',
            new_name='Favorite',
        ),
    ]
