# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0004_auto_20170721_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_quote', to='quotes_app.Quote'),
        ),
    ]
